# Schema for the configuration files of the kp_zadarma module.
kp_zadarma.settings:
  type: config_object
  label: 'KP Zadarma settings'
  mapping:
    zadarma_api_key:
      type: string
      label: 'API key'
    zadarma_api_from:
      type: string
      label: 'API parameter from'
    zadarma_api_secret:
      type: string
      label: 'API secret'
    zadarma_api_predicted:
      type: boolean
      label: 'API parameter predicted'
